image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Dependencies
          - apt update
          - apt -y install cmake build-essential lcov curl mercurial lsb-release wget
            libtinyxml-dev libxml2-utils ruby-dev libboost-dev
            python-psutil cppcheck
          # Static checking before building - fail fast
          - sh tools/code_check.sh
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt update
          - apt install -y
            libignition-math4-dev
            libignition-tools-dev
          # SDFormat
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make test
          - make coverage
          - bash <(curl -s https://codecov.io/bash)
          - make install
          # Examples
          - cd ..
          - cd examples
          - mkdir build
          - cd build
          - cmake ..
          - make -j4
          - ./simple ../simple.sdf
