name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'libtinyxml-dev libxml2-utils ruby-dev python-psutil libignition-cmake2-dev libignition-tools-dev libignition-math6-dev liburdfdom-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

